name: tests
on:
  push:
    tags:
      - '*'
env:
  REGISTRY_IMAGE: dutov/gitea
  REGISTRY_VERSION:  1.24.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git-checkout
      uses: actions/checkout@v4

    - name: kaniko-build
      uses: aevea/action-kaniko@master
      with:
        image:    ${{ env.REGISTRY_IMAGE }}
        username: dutov
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        tag: ${{ env.REGISTRY_VERION }}

